#!/bin/bash
#
# Check if your code matches the coding guidelines.
# See http://developers.fork-cms.be/?title=Coding_standards for more.
#
# Make sure your CLI has enough memory. Either hack the phpcs file:
#     1. sudo vim /usr/bin/phpcs # Your location may vary
#     2. add "ini_set('memory_limit', '2048M');"
# or edit your command line php.ini file:
#     1. sudo vim /etc/php5/cli/php.ini # Your location may vary
#     2. search for memory_limit and set it to -1 or a fixed (but high enough) value
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# check if phpcs is installed
type -P phpcs &>/dev/null || { echo "PHP CodeSniffer is not installed, run 'pear install PHP_CodeSniffer'." >&2; exit 1; }

# determine the absolute path of the base directory
base_dir="$(php -r 'echo realpath($_SERVER["argv"][1]);' "$(dirname "$0")/..")";

# run it
phpcs -v --standard="$base_dir/tools/codesniffer/Fork" --ignore="$base_dir"/default_www/backend/core/js/tiny_mce,"$base_dir"/default_www/frontend/cache,"$base_dir"/default_www/backend/cache,"$base_dir"/default_www/install/cache,"$base_dir"/default_www/docs,"$base_dir"/tools,"$base_dir"/library/external --extensions=php --report=full "${@:-$base_dir}"
