#!/bin/bash
#
# Remove all cache files.
#
# @version	1.1.0
# @author	Johan Ronsse <johan@netlash.com>
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# determine the absolute path of the base directory
base_dir="$(php -r 'echo realpath($_SERVER["argv"][1]);' "$(dirname "$0")/..")";

# go to the base directory so we do not need to use "../"
cd "$base_dir";

# find and delete the relevant files
find \
	default_www/install/cache/ \
	default_www/frontend/cache/cached_templates/ \
	default_www/frontend/cache/locale/ \
	default_www/frontend/cache/minified_css/ \
	default_www/frontend/cache/minified_js/ \
	default_www/frontend/cache/navigation/ \
	default_www/frontend/cache/statistics/ \
	default_www/frontend/cache/compiled_templates/ \
	default_www/backend/cache/analytics/ \
	default_www/backend/cache/cronjobs/ \
	default_www/backend/cache/locale/ \
	default_www/backend/cache/mailmotor/ \
	default_www/backend/cache/compiled_templates/ \
	! -name '.gitignore' -type f -print -delete;

echo 'All done! Cache files removed.';
