#!/bin/bash
#
# Generate reports from PHP CodeSniffer, PHP Mess Detector, PHP Depend and phploc.
#
# @version	1.0.0
# @author	Tijs Verkoyen <tijs@sumocoders.be>

# determine the absolute path of the base directory
base_dir="$(php -r 'echo realpath($_SERVER["argv"][1]);' "$(dirname "$0")/..")";

# go to the base directory so we do not need to use "../"
cd "$base_dir";

# create folder
mkdir -p 'tools/reports';

# run PHP Code Sniffer
echo '* Spawning PHP Code Sniffer...';
phpcs -v --standard=tools/codesniffer/Fork --ignore=default_www/backend/core/js/tiny_mce,default_www/frontend/cache,default_www/backend/cache,default_www/install/cache,default_www/docs,tools,library/external --extensions=php --report=xml "$base_dir" > tools/reports/phpcs.xml &

# run PHP Mess Detection
echo '* Spawning PHP Mess Detection...';
phpmd . xml codesize,unusedcode,naming --exclude default_www/backend/core/js/tiny_mce,default_www/frontend/cache,default_www/backend/cache,default_www/install/cache,default_www/docs,tools,library/external --reportfile tools/reports/phpmd.xml &

# run PHP Depend
echo '* Spawning PHP Depend...';
pdepend --jdepend-chart=tools/reports/pdepend_chart.svg --overview-pyramid=tools/reports/pdepend_pyramid.svg  --summary-xml=tools/reports/pdepend.xml --suffix=php --ignore=default_www/backend/core/js/tiny_mce,default_www/frontend/cache,default_www/backend/cache,default_www/install/cache,default_www/docs,tools,library/external . > /dev/null &

# run PHP Loc
echo '* Spawning phploc...';
phploc --log-xml tools/reports/phploc.xml --suffixes php . > /dev/null &

# wait for all background processes to finish
echo 'Waiting for spawned processes to finish. This will take a while...';
wait;

# tell user
echo 'All done!';
